// <auto-generated />
using AspNetCoreEFCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreEFCore.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreEFCore.Models.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama");

                    b.Property<string>("BolumAdi");

                    b.Property<int>("UniversiteId");

                    b.HasKey("BolumId");

                    b.HasIndex("UniversiteId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("AspNetCoreEFCore.Models.Universite", b =>
                {
                    b.Property<int>("UniversiteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniversiteAdi");

                    b.HasKey("UniversiteId");

                    b.ToTable("Universiteler");
                });

            modelBuilder.Entity("AspNetCoreEFCore.Models.Bolum", b =>
                {
                    b.HasOne("AspNetCoreEFCore.Models.Universite", "Universite")
                        .WithMany("Bolumler")
                        .HasForeignKey("UniversiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
